[project]
name = "Basic-FastAPI-Test"
version = "0.1.0"
description = "A basic implementation of FastAPI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
]
